### ISSUE TITLE
Having a problem on understanding a cell representation

### ISSUE THREAD

**Issue by f4nku4n** [fmsnew/nas-bench-nlp-release#19]
Hi guys, I opened this issue not because of having problem in the source code but I have a problem on understanding a cell representation and I need your help. Can you guys help me to show the difference between 2 below cells:
- {"f": {"op": "linear", "input": ["x", "h_prev_0"]}, "h_new_0": {"op": "activation_tanh", "input": ["f"]}}
- {"node_7": {"op": "linear", "input": ["x", "h_prev_0"]},  "h_new_0": {"op": "activation_tanh", "input": ["node_7"]}}

Does have the differences or they represent to the same cell structure?
Thank you so much.

**Comment by fmsnew** [comment]
Hi! These cells have the same structure.
